(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | ref'mk : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments ref'mk {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | ref'mk x => x
  end.

Parameter factorielle: Numbers.BinNums.Z -> Numbers.BinNums.Z.

Axiom factorielle_zero : ((factorielle 0%Z) = 1%Z).

Axiom factorielle_succ :
  forall (n:Numbers.BinNums.Z), (0%Z <= n)%Z ->
  ((factorielle (n + 1%Z)%Z) = ((n + 1%Z)%Z * (factorielle n))%Z).

Parameter n: Numbers.BinNums.Z.

Axiom Requires : (0%Z <= n)%Z.

(* Why3 goal *)
Theorem factorielle_ascendant'vc :
  ((factorielle 0%Z) = 1%Z) /\ (0%Z <= 0%Z)%Z /\ (0%Z <= n)%Z.
Proof.


Qed.

